### ISSUE TITLE
Custom percent in "Fill stat values"

### ISSUE THREAD

**Issue by janprusak** [SnosMe/awakened-poe-trade#104]
Hi, I'm new here. I don't know where else to post feature requests.
I would like to have:
1) "Fill stat values" in the Options with an editable value, not just +-10% (usually +-20% works better for me)
2) ~Some user interface scaling. I have a 32" 4K monitor with 100% scaling (so 1:1) and the interface is pretty small. It would be great If I could change the awakened poe trade scaling to cca 125-200%.~

Thanks

**Comment by ThorTheGray** [comment]
I second the idea of adding a scaling feature. I run 3440x1440 and it is so small. Idk why scaling is so rare on these tools.

**Comment by SnosMe** [comment]
Windows built-in scaling is working with APT. Do you have issue with it?

![image](https://user-images.githubusercontent.com/4292308/84414997-cefc7480-ac1a-11ea-9a84-bae25bf016dd.png)

**Comment by ThorTheGray** [comment]
PoE doesn't play well with that feature if you are using windowed mode. A lot are using this mode due to the problems vulkan introduced with overlays not being able to gain focus over the game window. I just attempted using the windows scaling with windowed fullscreen. Ctrl+Alt+F(I changed from D) works in windowed fullscreen but Ctrl+F does not. Going to 150% scaling looks good if I use Ctrl+Alt+F. So maybe we just have to wait for a fix from GGG, not sure since I am no expert on vulkan.
