### ISSUE TITLE
Feature Request: Pricecheck Hotkeys

### ISSUE THREAD

**Issue by Furioslyr** [SnosMe/awakened-poe-trade#110]
First off I'm so glad I found this PoE tradetool!  I love it and thanks so much for it!
I have a small request.  Currently to conduct an 'auto-hide price check' one has to use ctrl or alt + d.  I would prefer to be able to use 'auto-hide pricecheck mode' without having to hold down the ctrl key. Would it be possible to make it so I can set the hotkeys to be the opposite?
-Price check auto-hide mode, 'd' only
-open without auto-hide, 'ctrl + d'
.....
So I found the config file and edited it to my liking (shown below).  It would be nice if there was an option in settings.
"priceCheckKey": "D",
"priceCheckKeyHold": "",
"priceCheckLocked": "Ctrl + D",

**Comment by SnosMe** [comment]
Unfortunately no, because you will not be able to type "D" letter in chat/search boxes.
Are you ok with that now?
Also, there is an option in Debug section, enable "Hook", then you will be able to use D later.
It is on your own risk, every time you press "D" Ctrl+C will be pressed also.
![image](https://user-images.githubusercontent.com/4292308/84411989-3f08fb80-ac17-11ea-907c-9a2fa65a65ad.png)

**Comment by Furioslyr** [comment]
Thank you for the reply!  I guess I want to be able to type the 'd' key in chat huh?  lol.  I switched it to ctrl+d for autohide search, and ctrl+f for non autohide (locked).
