### ISSUE TITLE
Macros bring up Esc Menu

### ISSUE THREAD

**Issue by Nethstar** [SnosMe/awakened-poe-trade#1116]
Chat macros, regardless of what they're bound to or set as, will always bring up the Esc Menu.

Debug shows after pressing the hotkey, it automatically presses escape.
![2023-09-22 13_50_53-Awakened PoE Trade](https://github.com/SnosMe/awakened-poe-trade/assets/145772305/4fa8c6c1-4159-4bcc-937c-ea6717d650fc)

**Comment by SnosMe** [comment]
I indeed press Escape to restore your chat history

https://github.com/SnosMe/awakened-poe-trade/blob/b446c617cc1d4970067c209cf172a5dd93fcf72a/main/src/shortcuts/text-box.ts#L39C1-L43

But it won't open menu, because I press Escape to close the chat.
What you observe is unique to you, check other programms etc.

**Comment by SnosMe** [comment]
> In regards to using Esc to close the chat, isn't that what the "press enter" toggle does too?

As I said it's used to restore your "ArrowUp" history in chat.
You can see in the code snippet above that I send message with Enter, then open chat with Enter again to restore history, the press Escape instead of Enter, because my intent is obviously not to send your previous message.

The issue you see is only specific to your setup, I can't help
