### ISSUE TITLE
Price check bug Forbidden Flesh Bomb Specialist

### ISSUE THREAD

**Issue by LeGycz** [SnosMe/awakened-poe-trade#1123]
Using price check on Forbidden Flesh with "bomb specialist" gives wrong data informations.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/140955553/32d92ce1-e277-42fe-9007-5ab98fd9f8e3)

![image](https://github.com/SnosMe/awakened-poe-trade/assets/140955553/37357d3a-6be8-4a56-9322-cf06af186c1d)

**Comment by zao** [comment]
This is still a problem in the wild.
The underlying reason is that Bomb Specialist changed node ID in the passive skill tree in 3.21, from 51462 to 47778.
`stats.ndjson` still has the old ID, which makes trade searches for Bomb Specialist look up Like Clockwork.
It incidentally doesn't have the ID for Like Clockwork at all.

**Comment by zao** [comment]
Veteran Bowyer is similarly affected based on data files, which should turn into Master Distiller on the trade site.
There's some stale entries in the APT data file for ascendancy nodes that have been removed, are unused, or even turned into a keystone:
"Powerful Precision", "[UNUSED] Slamako, Slam's Slam", "Prayer of Glory", "Shaper of Desolation", "Wicked Ward", "Beacon of Ruin".
