### ISSUE TITLE
hotkey to open trade directly

### ISSUE THREAD

**Issue by johnnypr0x** [SnosMe/awakened-poe-trade#116]
Can you make a hotkey command where we can go to the poe.trade site directly? in poe trade macro it was ctrl + q

**Comment by Quazaka** [comment]
Its 2020, it's illegal to use poe.trade. 
Joke aside. I will highly recommend that you start getting familiar with the official trade side. It is faster, more reliant and are much less likely to show items that have long been sold.

**Comment by johnnypr0x** [comment]
I mean a way to get directly to https://www.pathofexile.com/trade/ with the item in the search.

**Comment by SnosMe** [comment]
@johnnypr0x what's bad for you with the current approach to clicking on the arrow button?

**Comment by SnosMe** [comment]
- It's not possible to guess with which set of filters trade-site must be opened.
- Filling all available filters will require removing unnecessary ones, not filling all will require backtracking to game.
  - When new patch is out some data in game files may change and user will miss stats. When new league is out some basetypes not known yet to tool and it will also work misleadingly.
- There are also issue with bulk priced items, it's not possible to know which chaos or exalt page to open without, sending request first, since no GUI is shown and response not instant user feels it laggy.
  - There are also such things as Cloudflare's anti-bot captcha, realm maintenance, rate-limiting.
- Pressing hotkey without action

Handling all above error cases, creating messages for them, doesn't make sense for me.
Double "Trade - Arow" button is good enough, all errors in one place, just one-click to open browser, full observability that tool works/parses item correctly.
