### ISSUE TITLE
Feature request: poe-antiquary support

### ISSUE THREAD

**Issue by gobacktogo** [SnosMe/awakened-poe-trade#117]
hey, 
could you add support for https://poe-antiquary.xyz/? apparently the old trade macro had this as well.
thanks for your work!

**Comment by SnosMe** [comment]
What value it will bring to APT.
poe-antiquary is primarily used to plan your next build at league start, or when you plan to buy item, because item is NOT in your inventory now you cannot open poe-antiquary.
PoE's meta is so dynamic that history on that large time span has no value. Have you predicted that "Badge of the Brotherhood" will be 7x price compared to Delirium, almost reaching price of HH.
