### ISSUE TITLE
Price check HUD display format UX has no context 😕 

### ISSUE THREAD

**Issue by dewblackio2** [SnosMe/awakened-poe-trade#1198]
> [!NOTE]
> This is a request from a few new poe players (myself and friends) who've lost value on items sold due to confusion and lack of understanding. Please keep in mind that this is our opinion to try to help other new players from not experiencing the same mistakes we made.
# The Top Level Price Check Display Format Is Confusing For The Inexperienced
As a new PoE player myself, having friends who have joined me in this venture over the past few months, whenever we've price checked items for the first few times, we've all been very confused by this formating:
![image](https://github.com/SnosMe/awakened-poe-trade/assets/6306438/29d681ea-916c-41b9-8ced-eba2a8a8d07e)
### Reasons for the confusion:
- ```item -> 1 / 2.1x chaos``` looks like ```1 item is worth 2.1x chaos```

To experienced players, or those familiar with the currency/bulk format, this makes perfect sense. The issue is that there is no context for the format or what the numbers represent unless you are already familiar with it, or are able to learn it from searching as shown here:
![image](https://github.com/SnosMe/awakened-poe-trade/assets/6306438/b11035b5-432f-4944-8a6c-f7974a93e0e6)

# Potential solutions
- There should be a clear indication of the item and currency relationship rather than putting it behind a learning curve for newer players:
![image](https://github.com/SnosMe/awakened-poe-trade/assets/6306438/729ecc47-2cef-461d-bbc3-8ce3b6dd45d1)
- Provide a header above the display string to indicate the format like what is done within the table:
![image](https://github.com/SnosMe/awakened-poe-trade/assets/6306438/ebc33bbf-b8d6-413a-bfb5-350f89c37fbd)

> Additionally for either of the implementations above, you can allow users to configure the display format to their liking, but I feel the initial display format when first installing the application should be more descriptive for inexperienced players.

**Comment by SnosMe** [comment]
you're not the first one who mentions this.
1. It's consistent with ![image](https://github.com/SnosMe/awakened-poe-trade/assets/6306438/ebc33bbf-b8d6-413a-bfb5-350f89c37fbd)
2. It's 3rd grade math: 1item=fraction of chaos orb
3. If you skipped 3rd it's even better, because using poe.ninja price for selling in bulk is kinda wrong, price depends on stack size

**Comment by freezerain** [comment]
In the context of not trash items (>1c), the price of bulk as far as I understand is thight to item quantity and not its price:
1) if you want to sell part of the stack of 2000 wisdom scrolls: 10 chaos / 352 scolls - wich means you want atleast 10chaos trade
2) if selling by quant for the stack of 10 exilted orbs: 39 / 3 - wich means you want sell atleast 3 items.

In the app ninja average price is shown relatively to chaos: 1/2.1 on initial OP screenshot
however when an item price checked I imagine people expect to see item "price" not "item amount needed to reach 1 chaos"
I clearly remember how it was confusing at first and I offering another change to this price indicator:
In the OP case instead of showing 1 / 2.1, show 0.47/1

benefits of  0.47/1: 
-you showing not bulk size but actually the PRICE of the item
-you can now drop trailing 1 item quant and just show the PRICE (0.47c)

**Comment by SnosMe** [comment]
Related items, another case to not change it.

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/6ace49f3-5f43-4479-b546-850b73176256)

**Comment by dewblackio2** [comment]
I understand the intent is to display it as a fraction so we can avoid floating point number messiness, and it makes it consistent with bulk currency trading implementations everywhere. I believe, and correct me if i'm wrong here, that this feature is intended to be an "at a glance" implementation providing a quick insight into what an item is worth, and as a new PoE player, having to interpret it without context as to what the numerator and denominator represent makes it tedious the first time you use it.

Overall, yes the fractional representation makes sense to those who understand the inherent numerator and denominator roles following bulk selling principles in game, and I feel there just needs to be an indication of what those numerator and denominator values are, as shown from the table column header here: 
![image](https://github.com/SnosMe/awakened-poe-trade/assets/6306438/f67cb5c7-56f3-4409-955e-c07eef804a8a)

Regardless of a change being implemented, my goal with this request was just to make the tool more accessible for those who are looking to try the game out before the release of PoE 2 the following year, as not everyone inherently understands these principles immediately, and small details like that don't go underappreciated in that regard.
