### ISSUE TITLE
Overlay not working on Legion Go

### ISSUE THREAD

**Issue by ciceroripi** [SnosMe/awakened-poe-trade#1206]
I have this tool working great on my desktop, but when I try to use on my Legion Go nothing works.
Ctrl+D does nothing at all.
Shift+Space opens a white screen on top of PoE with nothing on it. The only way to get it out is forcing closing apt.

The game is in Windowed mode, and I have other tools that work, just apt that doesn't.

I tried changing resolution of the game, of the device, display %. but nothing seems to work.

I found a few black screen bugs, but no white ones.

**Comment by ciceroripi** [comment]
Found the issue, it the screen ratio or the fact that is a portrait screen.
1280x800
1920x1200
2560x1600
It is inverted like that as the screen is portrait, but I only use as landscape.
O plugged it into a 1920x1080 TV and it works.

**Comment by ciceroripi** [comment]
Anyway I work around this issue?

**Comment by cykotix** [comment]
Chiming in that I have the same issue.  It's definitely due to the resolution.  Haven't found out how to fix it yet.

**Comment by cykotix** [comment]
I think I got it working, but it's a temporary fix.  I know enough to tinker, but I also know this won't work as a long term fix.  I also don't know how to cross-platform compile this.  If anyone knows how to target a platform so I don't have to compile on Windows, that'd be great.  I initially compiled on Linux and I got an AppImage output instead of the win32 stuff I wanted.  I just ended up building in on Windows instead, but I'd expect I could target win32 and build on linux if someone knows how to do that.

That said, the Legion Go has a portrait display.  Windows has the display in `Landscape (flipped)` so it is orientated the correct way.  Within `main/windowing/OverlayWindow.ts` it has `width: 800` & `height: 600` hardcoded.  I changed that to `width: 800` and `height: 1280` to match the lowest resolution of the Legion Go, recompiled following the DEVELOPING.md instructions.  I ran the newly compiled bin and now I can `Shift + Space` without the white window and it shows the configuration screen.  Something is still slightly off but it at least appears.  More importantly, I can `Ctrl + D` over an item and I get the price overlay again.

For a long term fix, rather than hardcoding the width and height, either maybe make it a config variable?  Or perhaps auto detect resolution & orientation #when launched?  Unfortunately, what I've done thus far is kind of the end of my expertise.  Hopefully some else can use this to figure out a better approach.

**Comment by cykotix** [comment]
Well, it _was_ working but now I'm back to the white screen.  Back to the drawing board...

**Comment by cykotix** [comment]
I revisited this recently and I was still getting the white screen overlay in the latest 3.25 versions.  At this point I suspected it had something to do the AMD GPU drivers, or what was selected in PoE (DX11/12 or Vulcan).  Changing the renderer made no difference.  I ran DDU and installed the latest AMD AFMF2 drivers - still no change.

I decided to try Bazzite which required a reformat and ultimately decided to switch back to Windows.

I'm prefacing all this because rather than use Lenovo's Recovery Media to reinstall Windows 11, I used Microsoft's installer and simply downloaded all the drivers from their support website (stock GPU drivers still).  Something in Lenovo's Win11 image must be causing the issue.  Switching to stock Win11 and this software works.  Lenovo's image seems close to stock Win11 but I have no idea what was causing the issue.  It's possible *any* reinstallation of Win11 might have also solved the issue too - Lenovo's recovery included - but I didn't test that.

So if you have a Legion Go and you get a white screen overlay, consider reinstalling Win11 using a stock Microsoft ISO instead.  That fixed it for me.

And for bonus points, I got rid of Legion Space and switched to Handheld Companion and setup keybinds to work with the overlay.  Works wonderfully.

**Comment by stozzi** [comment]
I was experiencing the same issue, no overlay rendering on the Go or on an external display.
Once I made the external display separate and not mirrored so I could use a 16x9 resolution it works.
1920x1200 renders a pure white overlay when I hit shift+space, with a resolution of 1920x1024 it works perfectly fine
