### ISSUE TITLE
No longer checks for corruption in jewels

### ISSUE THREAD

**Issue by FranyLeidy** [SnosMe/awakened-poe-trade#1320]
Couldn't check other bases, but using the corrupted filter on jewels doesn't work.

**Comment by 0x111BA6FA** [comment]
corrupted toggle dont work for any item, checked on gems and body armour
for corrupted item - toggle works fine - its OK
for non-corrupted item toggle do not anything

also, i think this toggle should have 3 positions like on trade site: Any, Corrupted, Non-Corrupted

**Comment by SnosMe** [comment]
@0x111BA6FA Being corrupted has no upside, so I default the search to "Any" to give a fair price.
There is [not much items](https://www.poewiki.net/wiki/Corrupted#List_of_unique_items_related_to_corrupted_items) that benefit from having corrupted items, and because Adorned is pretty popular one I've added it as exception. No plans for 3-position filter.
