### ISSUE TITLE
Weapon DPS is calculated incorrectly

### ISSUE THREAD

**Issue by arvidsson89** [SnosMe/awakened-poe-trade#1413]
Weapon DPS in ctrl+D screen shows incorrect DPS with 20 quality.
Please see the screenshot.

![2024-08-01 090411](https://github.com/user-attachments/assets/bbc46ee0-2f79-4dc0-9761-7e86fa9985a6)

Inputting the weapon in POB shows a higher DPS, while manually calculating the DPS it shows POB is correct while awakened POE trade is off the mark by a lot.

```
Item Class: Two Hand Axes
Rarity: Rare
Vengeance Song
Karui Chopper
--------
Two Handed Axe
Physical Damage: 331-534 (augmented)
Elemental Damage: 2-7 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.21 (augmented)
Weapon Range: 1.3 metres
--------
Requirements:
Level: 58
Str: 151
Dex: 43
--------
Sockets: R G 
--------
Item Level: 82
--------
133% increased Physical Damage
Adds 2 to 7 Cold Damage
15% increased Attack Speed
+34% to Global Critical Strike Multiplier
21% chance to cause Bleeding on Hit
Adds 21 to 40 Physical Damage (crafted)
--------
```

**Comment by wisnia74** [comment]
@arvidsson89 Awakened PoE trade isn't really wrong per se, it counts DPS decently.

[It takes an **average** amount of damage your weapon makes per hit](https://github.com/SnosMe/awakened-poe-trade/blob/f252d5645707bc21fcc6be2c34f7e12ed4baef76/renderer/src/parser/Parser.ts#L552) and [multiplies it by attack speed](https://github.com/SnosMe/awakened-poe-trade/blob/f252d5645707bc21fcc6be2c34f7e12ed4baef76/renderer/src/web/item-check/ItemInfo.vue#L47).

So in your case:
- your phys dmg per hit is `331 - 534` so your **average pDPS** will be `((331 - 534) / 2) * 1.21`
- your ele dmg per hit is `2 - 7` so your **average eDPS** will be `((2 - 7) / 2) * 1.21`
- given your average pDPS and eDPS, when we add those together your **average total DPS** is `528.77` which gets rounded to `529` by Awakened PoE trade and is put inside `min` tag for `Total DPS`

I'm not sure why `Total DPS` shows `573` though, but it's **not untrue** because if we counted your **top total DPS** it would be `654.61` (`(534 * 1.21) + (7 * 1.21)`)

So to be 100% correct:
- your min total DPS is `402.93`
- your average total DPS is `528.77`
- your max total DPS is `654.61`

It doesn't make sense at all to display all those values in such a small window I guess, so Awakened PoE trade shows averages most of the time.

The fact that you mentioned PoB showing bigger DPS values makes me wonder if you realise, that it counts any DPS values **in relation to your current equipement, passive skills and configuration settings**. It just looks at the whole picture, whereas Awakened PoE trade looks only at the weapon at hand.

**Comment by arvidsson89** [comment]
Thanks for the explanation
