### ISSUE TITLE
Item mods on poedb

### ISSUE THREAD

**Issue by Hillgrove** [SnosMe/awakened-poe-trade#160]
Wonderful tool. Hope you will keep on adding to it.

I have a few feature requests that I've come to enjoy from other tools.

Examples from Trademacro:
1. ~Custom Search (Alt-I): gives a search box to allow you to search the trade for an item matching the input. Example: Search for "Monstrous Treasure"~

2. ~Highlight Item (Ctrl-F): Automatically inputs the ItemBase into the search bar. Example: Use on a rare Convoking Wand called "Kraken Cry" and it searches for "Convoking Wand", use on a Chance Orb searches for "Chance Orb", use on a "Elemental Weakness" gem, searches for "Elemental Weakness".~

3. ~Highlight Item Alternative (Ctrl-Alt-F): Searches for the Rarity type in most cases. When used on a gem it will search for "rarity: gem", used on a Transmute Orb searches for "rarity: Currency". Not entirely sure how it's coded but the Trademacro have some outliers, like if using on a Goliath Chest plate it searches for "Armour:" instead, a flask searches for "consumes" and "Flask".~

4. Look Up Affixes (Ctrl-M): When used on an item it takes you to that item poedb.tw mod page. Used on a Bone Helmet takes you to https://poedb.tw/us/mod.php?cn=Helmet&an=str_int_armour for example.

5. ~Trademacro can Ctrl+Mousewheel scroll between tabs without zooming in and out. Small but welcome change.~

6. ~Weapon DPS (Ctrl-C): This tells how much physical or elemental DPS a weapon has~

**Comment by SnosMe** [comment]
1. Will be tracked in #164 
2. Stash search widget is how it's implemented in APT
3. Stash search widget is how it's implemented in APT
![image](https://user-images.githubusercontent.com/4292308/86513075-d5dc6880-be0f-11ea-8fe5-c0101a902410.png)
4. Planned
5. Not possible due to different architecture
![image](https://user-images.githubusercontent.com/4292308/86513115-2bb11080-be10-11ea-83b6-ab99b04bfe36.png)
![image](https://user-images.githubusercontent.com/4292308/86513118-2fdd2e00-be10-11ea-900c-e33a6964021e.png)
6. Planned, however in most cases you alredy can see it in price check window (it might fall under toggle switch also)

**Comment by Hillgrove** [comment]
I'm sad you feel the "widget" is a fair replacement of the functionality of the mentioned feature requests. But it's your app and you ultimately decide.

I will keep using Trademacro.
