### ISSUE TITLE
Stash tab scrolling with rightclick+Mouse Wheel

### ISSUE THREAD

**Issue by cirf** [SnosMe/awakened-poe-trade#201]
it would be nice to have this option aswell

**Comment by SnosMe** [comment]
- Your second hand is always on keyboard
- Your hand is always on Ctrl because it's how you move items between inv/stash
- Your hand is always on Ctrl because you make price check (default hotkey)

This request is super niche, and has some technical problems too, I can't dedicate time to it because of technical and rationale I wrote above. I'll accept PR if someone wants to.

**Comment by cirf** [comment]
> * Your second hand is always on keyboard
I really like sorting my stash tab with one hand :)

> * Your hand is always on Ctrl because it's how you move items between inv/stash
I mapped ctrl-click to a mouse button, so no for me.

> * Your hand is always on Ctrl because you make price check (default hotkey)
I sort stash tabs much more often then i do price check, so also a no for me.
I got used to this key combo because poe trade macro has this and i am still looking for a replacement to this tool.

> This request is super niche, and has some technical problems too, I can't dedicate time to it because of technical and rationale I wrote above. I'll accept PR if someone wants to.
I understand, thanks for reply!
