### ISSUE TITLE
Overlay stuck

### ISSUE THREAD

**Issue by x912** [SnosMe/awakened-poe-trade#215]
After checking a price with Ctrl+D while holding Ctrl the overlay got stuck. it believes that it's closed so overlay is not listening to any clicks and you *could* play the game. the UI is still visible though.

I have no idea how this is replicatable but I have no option but to uninstall right now since reopening the overlay does nothing

**Comment by SnosMe** [comment]
IIRC remember such thing can only happen on Window 7 with enable Hardware Accleration 

![image](https://user-images.githubusercontent.com/4292308/94553825-c24f6b00-0261-11eb-9ebb-b405bf02f503.png)

Otherwise, it's indeed not reproducible for me.

**Comment by Blitz54** [comment]
Having the same problem very consistently here, although at random times. I haven't found an exact way to reproduce it, but it happens once or twice a session usually. Only started happening since I started this league, during settlers I didn't have the problem from what I recall.

I can't find that hardware acceleration toggle in the settings, where should I be looking?

I'm on Windows 11, DX12 in poe, adaptive VSync, 1080p windowed full screen. Much thanks.

**Comment by Motherpigeon** [comment]
> Having the same problem very consistently here, although at random times. I haven't found an exact way to reproduce it, but it happens once or twice a session usually. Only started happening since I started this league, during settlers I didn't have the problem from what I recall.
> 
> I can't find that hardware acceleration toggle in the settings, where should I be looking?
> 
> I'm on Windows 11, DX12 in poe, adaptive VSync, 1080p windowed full screen. Much thanks.

Indeed issue came back.
