### ISSUE TITLE
Hogging network data.

### ISSUE THREAD

**Issue by Heikkii** [SnosMe/awakened-poe-trade#246]
I've noticed since i started using Awakened Poe trade i get massive lagspikes in poe. Upon keeping resource monitor open i see that trade macro is using alot of network data from time to time (50000B/sec download.) Its completely random times, not when i use the macro. I have already disabled auto updates and it still keeps happening.

**Comment by SnosMe** [comment]
Code is open, check it, no hidden gems from you.

**Comment by Heikkii** [comment]
Nono, i'm just wondering what it is.

**Comment by SnosMe** [comment]
And I don't know too, because the only code under my control is in this repo. Electron is basically a Chromium that has 25 millions lines of code.
Screenshot with this paranormal activity also will be interesting to see.
The only thing that periodically updated is poe.ninja prices <1 MB every 10 mins.

**Comment by Heikkii** [comment]
I guess its that then, since it only lasts less than a second.
