### ISSUE TITLE
[Feature Request] Price Checking Settings

### ISSUE THREAD

**Issue by Schtenk** [SnosMe/awakened-poe-trade#271]
I would really love a way to choose which stats checkbox should be automatically checked when price checking an item, this would be nice to minimize the amounts of clicks needed to search for items with very similar stats that are important for the pirce.

The settings for this could be similar to the Map Check feature settings in APT.
This feature could even be taken further, for example to not check a stat if it's outside of a certain range or so on. 

Im not sure how much effort it would take to implement something like this so if its a bit much work to be worth it.

An alternative would be a setting to automatically check all stats and let the user instead uncheck the stats that are  they feel are important for the search (usually when checking an item there are more stats that are important than not for the price, this feature would then lead to less clicks).

Another alternative would be to similar to the one above would be add a "check all" function into the UI.

Thanks for your time and for this helpful program.

**Comment by SnosMe** [comment]
This a hard problem to detect if start worth to tick (N stats x N basetypes x Stat roll/trier x Current game meta). Human brain solve this problem easily, but I can't imagine how to describe it in program.
Even if you got this engine you still will scan every filter by eyes, because 1) lack of trust 2) can be bug 3) new stats appeared in game 4) ....

About selecting all stats see my comment in #264

**Comment by Schtenk** [comment]
I didn't mean for the stat be ticked based on any meta, predetermined data or engine.

My thought was for the user themselves to specify which stats they want to be automatically ticked in a form much like the Maps form in APT Settings where you select which map mods for the Map Check feature to warn about, for example:
The user can add stats like "+X to maximum life" which would then be automatically ticked when they use the price check feature.

This feature can be expanded on to allow for ranges or a minimum to be specified, so if a stat one an item is lower than the minimum or not in the range specified for that stat it would not be automatically ticked.

Thanks again for your time and fast response.

**Comment by SnosMe** [comment]
Please stop comparing this to maps.

---

Imagine you set threshold for life min=50

Take for example this boots

```
+23 to Evasion Rating
+26 to maximum Life
12% increased Stun and Block Recovery
Ignites you inflict deal Damage 10% faster
You have Tailwind if you have dealt a Critical Strike Recently
20% increased Movement Speed (crafted)
```

They have Tailwind, crafted MS and +26 life (T1: 24-28).
T1 life will not be ticked.

Ok, you say, you are removing min threshold.
Next item you check is Ring with +4 life, and... it's ticked, this life stat actually bad for price check because it narrows search for no reason. What I mean is you +4 life equals to any low roll prefix, but you are searching specifically for life. Blocked prefix = missing opportunity to use crafting bench.

Ok, you say, but we can add basetypes to condition. I hope you're happy because it's now combinatorial problem and what filling all stats will be same as manual editing .filter files, Neversink and team made a filterblade so you don't feel how it's bad...

**Comment by SnosMe** [comment]
I agree stats as Tailwind can be auto ticked but configuring this has to be done once for all users, without exposing it in UI like map stats.

**Comment by Schtenk** [comment]
Sorry if I wasn't clear english isn't my first language but map thing was more of how maybe the UI would look like for entering which stats you would want to automatically tick.

im not suggesting that the checkboxes should be locked from being changed on the Price Check screen but that the user can add stats which they feel are generally wanted on items to be ticked without having to do so manually.

**Comment by Schtenk** [comment]
Why did you delete my comment?

From your responses it seems like you are  missunderstanding me and making the assumption that I want the program to automatically determine which stats are good and tick them for me, that is not what im looking for.

I am only suggesting to be able either have all stats ticked(could be a setting for the default state of the checkboxes to be ticked or unticked) and be able to myself untick the stats in the price check window that I (as a user/any user) feel are less important for the search (usually fewer stats to untick than tick) or select which stats I would like to be ticked in a UI(doesn't have to be extremly specific like only tier 1 life but just life in general etc).

**Comment by SnosMe** [comment]
Because I said in previous comment how I would like to see this issue solved. Your comment just repeats what you said first and not trying to tell me counterarguments for https://github.com/SnosMe/awakened-poe-trade/issues/271#issuecomment-714565267

**Comment by Schtenk** [comment]
The argument you made in https://github.com/SnosMe/awakened-poe-trade/issues/271#issuecomment-714565267  assumes that this system can be perfect and that there won't be edge cases, but the system can't be perfect but what im advocating for is having to click less. if an item has a stat that is very low but autoticked by this system the user can untick that stat, this ofcourse means that the user has to use some judgment in what stats should be ticked every time they do a price check but it should generally lead to having to click less.
