### ISSUE TITLE
Configuration Option to Disable Auto-Pricecheck

### ISSUE THREAD

**Issue by tanis0** [SnosMe/awakened-poe-trade#273]
I'd like the option to disable the auto-search in the price check so that it will not run the search against the trade site (I assume poe.ninja is not an issue) until I mouse over the area where the searches appear (basically, like it works now after adjusting filters but without the initial auto-search).

If I want immediate results without changing filters, this would delay me less than half a second, but it would almost eliminate the time I spend waiting for the rate limit to expire. As it stands, I'm constantly up against the rate limit when using price checks because I tend to both check several items in a row and make adjustments to the filters pretty quickly, and then I have to sit there for 10+ seconds doing nothing while it resets.

**Comment by QUEWEX** [comment]
I agree, I would like to see an option to delay or control this. It's something I've been wanting to see since I started using Awakened.

The application is often submitting searches even while I'm in the middle of configuring exactly what it is on the item I am trying to search for this. This results in unnecessary searches which subsequently affects API rate limits. 

I think it would be good option to add in order to reduce the number of calls against the trade API - particularly given GGG themselves implemented the API rate limits so that requests don't overwhelm their trade site - and is a good software practice in general.

**Comment by Mar-vo** [comment]
To add to this, this might have been adressed already, but my friend actually got banned because of all the trade api requests this tool makes. That was a while ago right now, but i still often worry i'm making too much requests when i'm changing filters.
