### ISSUE TITLE
Using with external browser Manjaro KDE

### ISSUE THREAD

**Issue by binarydepth** [SnosMe/awakened-poe-trade#286]
Make an option to always open in external browser. This is for using without Compositing on Linux, I'm checking out AutoKey to see if can have this kind of features in native tools.

I did the fixes [here](https://www.pathofexile.com/forum/view-thread/2970019/page/1#p23728777) and now the app doesn't see PoE the Steam version

**Comment by SnosMe** [comment]
No, because: https://github.com/SnosMe/awakened-poe-trade/issues/116#issuecomment-702395635

Compositing on Linux is not a valid argument. The current state of things on Linux: compositing is shit implemented laggy thing and nobody improves it, because who cares? How many games you ever seen in the world that require an extra app on top of your game, probably 1 - PoE.

- Linux, no compositing: Enjoy how developers see PoE should be played
- Linux compositing: enjoy low FPS
- Windows: wow compositing is force enabled since Win 8, - no lags, no problems, "technology is here".

---
Meanwhile Windows improves rendering stack.
![image](https://user-images.githubusercontent.com/4292308/103460721-4dd50e00-4d21-11eb-89d1-d4fef62cac08.png)

**Comment by binarydepth** [comment]
You are seeing things from the outside though. I make some benchmarks with Proton experimental and got a stable 60 fps, surprisingly. Maybe I try playing again with compositing and post the benchmark. It's a feature request no no need for that. [Benchmarks](https://forum.garudalinux.org/t/my-benchmark-with-path-of-exile-zen-xanmod-and-tkg-bmq/8572/4)
