### ISSUE TITLE
Trade site request failed

### ISSUE THREAD

**Issue by Zakhaev31** [SnosMe/awakened-poe-trade#309]
Trade site request failed
Error: rate limited exceed
https://puu.sh/HavPz.png

i just cheked 10 items, on the ritual altar, then i cannot check anything.
Can u increase the limit, its so annoying, never had this issue on the old trade macro

**Comment by SnosMe** [comment]
This limit is set by GGG to keep trade site in working state at league start. Trade site always had limits, but now they are stricter. App automatically queues request and waits, so that you are not Rate limited. Unfortunately, there is still a small chance to hit rate limit, because of latency and server load on GGG end.
