### ISSUE TITLE
Portable version is not portable

### ISSUE THREAD

**Issue by ghost** [SnosMe/awakened-poe-trade#316]
Hi, thanks for keeping this great tool.

While the app itself is just a single exe file, its storing its data on /appdata/roaming/awakened-poe-trade/ and possibly some other stuff on /appdata/local/ with no aparent way of changing it.

i tried to 'portabilize' the app using [this code](https://superuser.com/a/1226026) but was to no avail

i think the general consensus for some app to be considered portable is that it should at least be able to store all of its stuff in the same folder (self contained) which is why im opening this issue

**Comment by SnosMe** [comment]
I never considered a portable version because it doesn't support auto-updates. 
The only reason it's provided is because of installation being stuck halfway for some people, but that doesn't seem to happen anymore, so I can remove this type of build.
"Portable" means app without installation step, rather than a truly portable version.
