### ISSUE TITLE
CTRL+Scroll function feels lacking.

### ISSUE THREAD

**Issue by Genuvien** [SnosMe/awakened-poe-trade#332]
When I CTRL+Scroll with Stash open, your mouse position affects if it will actually work or not, or if it will try to default zoom you in and out, while scrolling stash tabs.

The old POE Trade Macro you can use CTRL+Scroll with mouse position anywhere on screen with stash open and it will only scroll your stash tabs. 

Maybe could appropriate whatever was done in TM to get the scroll function to work everywhere. 

Love this macro btw, it's just that part, it drives me crazy.

**Comment by KennethHoff** [comment]
This started happening with 3.13 and it really is annoying. I've gotten used to it by now, but it's not ideal.

If you try ctrl+scrollWheeling while your cursor is over the stash window it starts "lagging" like that.

**Comment by Genuvien** [comment]
Well the old Trade Macro still works great with scrolling, so I'm running it until this gets fixed. For pricechecking I still use Awakened PoE Trade of course, just disable its ctrl+wheel scroll function. I combined them both into the same so they launch together. I'd rather just only have to run Awakened PoE Trade, its annoying though.

**Comment by SnosMe** [comment]
With 3.13 following changed:
1. Ctrl+Scroll (provided by game, not Awakened) now works only in `green zone` but previously worked in `red zone` too.
2. Ctrl+Scroll provided by game now refuses to scroll until game received stash tab items from the server. (I guess to reduce load on server, because with stash tab affinities now less need to scroll them, so in GGG's vision player should now jump to wanted tab using dropdown list).
*Arrow keys that also "scroll" stash tabs not blocked. At least for now.*

- ahk-poetm blocks mouse wheel input events and instead always sends arrow keys to game, so not affected by [2] change.
- Awakened cannot block them and has to stop sending arrow keys in `green zone` to prevent Double stash tab scrolling (game's bultin + arrow from app), so when cursor is in `green zone` you're affected by [2].

I'll fix scrolling for [1], but unfortunately we have to adapt to [2] change and live with it.

![image](https://user-images.githubusercontent.com/4292308/109854879-3e5e3c80-7c60-11eb-815e-86a05a805bb8.png)

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/commit/36e995c083b5627c438cc7e8220526f4bb6c0472
