### ISSUE TITLE
Add Stash tab scrolling without Ctrl to options menu

### ISSUE THREAD

**Issue by mafima** [SnosMe/awakened-poe-trade#335]
Please add an option to scroll through the stash tabs without holding Ctrl.
Currently I am using [poe trade marco](https://poe-trademacro.github.io/index.html) with rebinded marcos for that. (from Ctrl mousewheel to mousewheel only)

![image](https://user-images.githubusercontent.com/3407209/110765767-cd68e700-8254-11eb-8335-70b9e87c7795.png)

Created a Pullrequest for it: 
https://github.com/SnosMe/awakened-poe-trade/pull/336
please check code, i needed to change the type from bool to int

**Comment by mafima** [comment]
Here is the code required. Would like to do a mergerequest. 

src/main/shortcuts.ts
https://pastebin.com/m8w0uBij

src/web/settings/hotkeys.vue
https://pastebin.com/YqYCDxsh

**Comment by SnosMe** [comment]
No, because this conflicts with various scrolling controls (not an exhaustive list).

![image](https://user-images.githubusercontent.com/4292308/128056569-be3006d7-fc45-4264-9f84-a68e1aff82fa.png)

![image](https://user-images.githubusercontent.com/4292308/128056592-0a7aff54-eea9-4561-af2a-bf7b1687a57d.png)
