### ISSUE TITLE
Wrong text display in filter for Death's Oath

### ISSUE THREAD

**Issue by Noctis-** [SnosMe/awakened-poe-trade#338]
Attaching screenshot of the issue.

Death Oath's `You take 450 chaos damage per second for 3 seconds` appears in the filters as 
`you take 226 chaos damage per second for 226 seconds on kill`

![image](https://user-images.githubusercontent.com/6160139/111086010-d5cb6580-8565-11eb-982a-7aab9b8e79bc.png)

**Comment by SnosMe** [comment]
This is because it contains two stats in one line. And when there multiple stats average value is taken.

![image](https://user-images.githubusercontent.com/4292308/111086205-954af800-8523-11eb-9187-9c06f41a72ad.png)

`(450 + 3) / 2 = 226.5`

Here I'm searching for 226

![image](https://user-images.githubusercontent.com/4292308/111086239-bf9cb580-8523-11eb-854c-4a750d4afd36.png)

And no results for 227

![image](https://user-images.githubusercontent.com/4292308/111086246-c6c3c380-8523-11eb-9c07-480e2c072192.png)

Not a bug, this is just how the game works.

**Comment by Noctis-** [comment]
Cool. Cheers
