### ISSUE TITLE
Installer: Check VCRedist

### ISSUE THREAD

**Issue by diegoSloth** [SnosMe/awakened-poe-trade#37]
![](https://i.imgur.com/O8J0IoG.png)

https://imgur.com/a/4fvuw0d

**Comment by SnosMe** [comment]
Are you trying to run this in a virtual machine?

**Comment by diegoSloth** [comment]
No

**Comment by SnosMe** [comment]
Unfortunately, this problem is not at the application level, but at a lower level, to which I have no relation at all. Therefore, it will be difficult to understand why it does not work on your system.

As a continuation of guessing:
Do you use the LTSB version of Win 10 ?
Are you running it in an antivirus sandbox?
Have you tried the portable version?

**Comment by fragfaq** [comment]
@diegoSloth Try delete and reinstall **all**, what u can. Starting from Java and visual C ++ and ending with updates to the operating system. In the `Users\%Username%\AppData\`, in `Local` and `Roaming` folders, delete **everything** you are not familiar with, do not need it, and so on. Alternatively, you can try a cleaning program such as CCleaner. Check the integrity of the system files, or even better, use the system restore function if you made backup copies of the system. This is a mistake on the part of Windows, found in many programs, for example, in a discord. The latest versions of XenonTrade did not start on my system, dropping a similar error (it's good that I no longer need XenonTrade).
Since I myself did not solve this problem (the last measure was to completely reinstall the windows, but I did not do it), I can only share what I read in Google when I tried. GL.

**Comment by ReigardCl** [comment]
Same Error in a new SSD all is new in my pc just coping the old poe from old hdd

**Comment by SnosMe** [comment]
@ReigardCl Install VCRedist 2019 https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by ReigardCl** [comment]
Thx man thats is the solution thx u from CHILE Gracias.

**Comment by SnosMe** [comment]
Fixed in v1.0
