### ISSUE TITLE
Overlay keeps breaking

### ISSUE THREAD

**Issue by noqualms** [SnosMe/awakened-poe-trade#411]
Every time i do a price check, the overlay will open, and show prices, but I can't interact with the overlay, and it just sticks to the screen until I press the windows key to open / close the game window. I have deleted the app, re-downloaded, tried every different setting I can think of and checked google for, but I can't seem to fix the issue, it fixes itself for maybe a minute or two after opening / closing the app, and then it just breaks again.

**Comment by SnosMe** [comment]
Do you have same issue with previous 2.10.5 release?

**Comment by noqualms** [comment]
> 
> 
> Do you have same issue with previous 2.10.5 release?

Not that I remember happening, although I can't exactly remember when the 2.10.5 release was. This has only started happening about a week and a half ago.

**Comment by SnosMe** [comment]
> This has only started happening about a week and a half ago

Well, you need to find what caused this. Can't help you anymore.

**Comment by noqualms** [comment]
> 
> 
> > This has only started happening about a week and a half ago
> 
> Well, you need to find what caused this. Can't help you anymore.

Aren't you the creator of the app? How am I supposed to figure this out??

**Comment by SnosMe** [comment]
> Aren't you the creator of the app?

Even if I'm creator of application, it's not running in isolation, it's running in the OS and can be affected by other applications. Since this "bug" doesn't happen to me, I can't fix or guess what happens to you.  I would also like to add that it cannot be logged in. 

> How am I supposed to figure this out?? 

All the information I have is that it worked fine for you up to a certain point. Something happened on your PC and it stopped working.
