### ISSUE TITLE
Ctrl+F functionality from original trade macro would be nice thing to have

### ISSUE THREAD

**Issue by nolanmain** [SnosMe/awakened-poe-trade#47]
Sorry if issues is the wrong place

**Comment by 0ldi** [comment]
+1 its very needable and usefull.
Also missing:
1)make constant use of this button, not after searching (because if the app is temporarily blocked due to a large number of requests, there is no way to click it)
![image](https://user-images.githubusercontent.com/16578229/78455678-781d7080-76a8-11ea-896e-ce40e1c9827f.png)

2)-opening fast search (through the browser) with the stats selected by my item (like old ctrl + Q)

3)this:
![image](https://user-images.githubusercontent.com/16578229/78455513-85862b00-76a7-11ea-9d8f-ffa8942fd86f.png)

4)Optionable: the ability to search on poe.trade instead of pathofexile.com/trade (it may come in handy when official is down)

**Comment by RyuuOujiXS** [comment]
> +1 its very needable and usefull ctrl+F on item base searh
> Also missing:
> 1)![image](https://user-images.githubusercontent.com/16578229/78455678-781d7080-76a8-11ea-896e-ce40e1c9827f.png)
> make constant use of this button, not after searching (because if the app is temporarily blocked due to a large number of requests, there is no way to click it)
> ![image](https://user-images.githubusercontent.com/16578229/78459356-17e6f880-76c1-11ea-8f49-eb4f70cc4e00.png)
> 
> 2)-opening fast search (through the browser) with the stats selected by my item (like old ctrl + Q)
> 
> 3)this:
> ![image](https://user-images.githubusercontent.com/16578229/78455513-85862b00-76a7-11ea-9d8f-ffa8942fd86f.png)
> 
> 4)Optionable: the ability to search on poe.trade instead of pathofexile.com/trade (it may come in handy when official is down)

Imagine being so dumb that you hijack other issues for unrelated garbage.
