### ISSUE TITLE
No way to filter blueprints based on their base item type

### ISSUE THREAD

**Issue by tbarusseau** [SnosMe/awakened-poe-trade#496]
There is a huge difference in price between various Heist blueprints, and there is currently no way to restrict the search based on the blueprint's type.

For reference, poe-overlay-community-fork does allow you to restrict the search based on the blueprint's base item.

**Comment by SnosMe** [comment]
You can always click on name to activate more strict search by basetype.

![image](https://user-images.githubusercontent.com/4292308/151540341-c14fffaa-7941-4d79-a83b-cf86655da45d.png)

If I remember correctly, it's not selected by default because I've requested "Heist Target" filter from GGG https://www.pathofexile.com/forum/view-thread/3109852

**Comment by SnosMe** [comment]
I'll enable search by basetype for now.
