### ISSUE TITLE
Affixes on item search no longer showing

### ISSUE THREAD

**Issue by nmarkey10** [SnosMe/awakened-poe-trade#504]
Hello,
Recently I have been experiencing an issue where item search doesn't show affixes that can be checked.  Here is a screenshot of the issue:

![stats missing](https://user-images.githubusercontent.com/15642301/142763885-a170eac5-9790-44f0-9991-6cdeaeddfbb5.PNG)

I've attempted to uninstall, remove appdata and reinstall.  No success.  Any help would be appreciated!

**Comment by SnosMe** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/493#issuecomment-962249979

**Comment by nmarkey10** [comment]
@SnosMe , sorry, just saw the reply. It worked after changing it from Alt, to , but I cannot get it to work with Alt bound as Highlighting items and objects. Which is weird, because it has always been Alt. Still seems like there might be a bug to me.

**Comment by SnosMe** [comment]
So you didn't have a mouse button there, then it's likely AHK script or some program interfering with key presses. (not a bug)

**Comment by redrios** [comment]
I tried to move to F and X and couldn't, I price check with ctrl+d. I may have to revert back to alt for highlight, because althou I don't highlight to pricecheck, It won't show mods in search when highlight objects is not bound to ALT, is this normal?
When i press the 3 keys X or F then CTRL + D it does search for mods,, but i dont be trying the whole keyboard to see where i can move it.. ty
