### ISSUE TITLE
Sentinels are not supported yet

### ISSUE THREAD

**Issue by Xebtria** [SnosMe/awakened-poe-trade#639]
does not matter if normal (rare/magic) or unique sentinels, none of them are supported yet

**Comment by SnosMe** [comment]
This was discussed in Discord, and it was concluded that there was no point in supporting them.
This decision may be reconsidered if Sentinel goes into core game

I welcome you to post screenshots of what types of Sentinels you would personally buy on Trade site.
Or screenshots of Sentinels you've been able to sell (i.e. there's interest in them from buyers),
as well as why you wouldn't use one yourself.

**Comment by Xebtria** [comment]
I can see the point for rare/magic ones as I most likely will just use / run them myself, that is true.

But for example, I drop a unique one, I want to know whether I want to run it myself or maybe I can ignore it and sell it itself, but I have to manually go to trade and see. turns out the one I just found is worth fuck all, but I know there is this specific one (I haven't dropped/built it yet) which empowers specific map bosses (at least it was shown in the announcement I think?). This might be worth something, and I might want to sell it now because I don't care about empowering specific bosses yet, and might want to buy it later in the league because there is a challenge for it: https://i.vgy.me/0MQL64.png

again, I understand now that magic/rares might not be that useful to be supported, but at least uniques... why not?

**Comment by projectsix84** [comment]
Hi, just adding my two cents.. I've sold several after manually checking them. But that's a pain..  I have good ones that optimally I would run, but I just end up with way too many. There's a market for specific ones that I wouldn't use (like high quantity for expedition), some specific strats (delirium in abyssal depths with the passive node for higher lvl mobs), etc.. my point is not everyone is just slapping on decent ones and go. There are buyers for specific mods. I'd like to sell them and was hoping to see an update to support these. If its possible, that'd be awesome.  Thanks!

**Comment by SnosMe** [comment]
Support for unique Sentinels has been added.

**Comment by djarkan** [comment]
here is hiw to search a good sentinnel in our stash
type that in research: "(cy|el|rd|ab|ger|il|ion|ht|is|st|ual|um|ch) r"
only good one are highlited so i think there is a market for these
taken from Grimro video stream. https://www.youtube.com/watch?v=7sJna539C9o

**Comment by projectsix84** [comment]
Even blue ones can be good. I sold 2 magic expedition ones that were on bad bases for 90c each last night. The very high quantity ones are worth something too for the current magic find in Crimson Temple meta. And there's plenty of people who really don't like IDing, sorting, breeding them etc but they're still profitable to use so they'll buy any good ones.

I'd still really like to see support for these. As a few of us have been saying, there is a market for them and they are being traded. This tool is great and would make it so much easier to price check ones that you want to sell. I'm not complaining since it is free to use.. I'm just still holding out hope that they will be added :) I saw the update today and was hopeful. Either way, thanks for the work you do on this script!
