### ISSUE TITLE
Can we / do we want to - add tft prices to awakened?

### ISSUE THREAD

**Issue by Sykh** [SnosMe/awakened-poe-trade#674]
Just stumbled across their git
https://github.com/The-Forbidden-Trove/tft-data-prices/tree/master/lsc
where you get json prices for almost everything...

I am sure there are some cases where this can be usefull (contracts?)

**Comment by freezerain** [comment]
poe ninja is have everything that can be priced reliebly, there are no need to add another generic price source.

Poe ninja filter item prices by "confidence" while discord statistic channels only have raw data, developer will be responsable for creating "confidence" algho for discord data (trusting this data is another question).

Another responsability will be deliever information clearly to the user that can be a problem in some cases as source data is not very verbose in the first place. Look for example at map data, I think there are some maps with insane prices just because they sold once on server, or there was 2 day hype because of some YT guide, how to price them? ignore them? what percent of the data is relieble and how to verify this?

And dont forget that bulk price is a thing, and bulk price is purely arbitrary collision of seller greed and buyer impatience. How to price essences? Bulk price is based on poe ninja price * bulk multiplicater. Some of the essences are never byued by them self but like a ballast for higher tier essences driving total multiplicater down. Just look at WTS and WTB to see how value range is wide for the same item. 

And what about services? we cant even ctrl+d on them.
And if you cant price check services, relieble price check bulk and trust TFT sell data of rare trades that what is left to price check? A contracts? Deception 15c everything else 1c.

The problem is not in this app, TFT stuff will need to improve their analytics to actually price check something reliebly in auto mode.

P.S. if you will add this feature price will be abused like a dock whore by ghost trades with just a 6-12 bots easily

**Comment by SnosMe** [comment]
Can be added if only poe.ninja decides itself to use TFT provided data and reexports using poe.ninja api.
