### ISSUE TITLE
3.19, Replace Exalts with Divines on the search window

### ISSUE THREAD

**Issue by Marcehs** [SnosMe/awakened-poe-trade#694]
Currently, in standard, prices for divines have skyrocketed and exalt prices are nosediving.
In 3.19, we'll probably just need to have Divine orbs take the place of Exalts on the search window.  Maybe have an option to switch which is primary in settings until we see what happens with prices during the upcoming Kalandra league?

**Comment by SnosMe** [comment]
Too much coding for two weeks of "until we see".
Current plan is to wait for end of 1st week

**Comment by Fish013** [comment]
I'd say this is justified now

**Comment by dsf3449** [comment]
@Marcehs @Fish013 this was annoying me because I'm lazy, and also since people are adamant about listing their garbage as 0.2 divines or whatever, so I made this change:

![electron_WSkMDFsAxq](https://user-images.githubusercontent.com/25350725/185803189-ad3fb677-390a-477e-b6eb-03afe8902226.png)

I've created a PR [here](https://github.com/SnosMe/awakened-poe-trade/pull/706), but I assume since @SnosMe said they wanted to wait a bit before making changes, that it won't actually be merged.

Due to security concerns I won't distribute the `.exe` here, but you can build it from source yourself.
