### ISSUE TITLE
Can we get revealed wings on blueprints pls?

### ISSUE THREAD

**Issue by Sykh** [SnosMe/awakened-poe-trade#740]
I know you cant parse it but we could quick set it by hand to check if reavealing the bp is worth it, would be really convenient tbh

**Comment by SnosMe** [comment]
Currently, it's shown when you have 2+ reveled, but I can do it always.

Just to note: 
- this is because you can spec atlas for full revealed blueprints.
- you should sell markers instead of forcing people to do blueprint unrevealed by you
- the price of `(blueprint + markers to fully reveal it) > dropped fully revealed blueprint`, you will need to set price on the same level as  `dropped fully revealed blueprint` so you're actually losing by not selling markers. PS this seems logical to me, but I haven't checked real prices

![image](https://user-images.githubusercontent.com/4292308/189650103-a48b522a-9898-4dbb-81b7-dbc131f972e1.png)

**Comment by Sykh** [comment]
Hmm lets test this, i have a 3 wing - unrevealed -> 30c
It looks like markers go for 450:1
I still have Gianna reveals so a wing is 2-3k -> 4-6c

3 Wings revealed are selling for 60c (the cheapest, might go for 70c), i sold a 4 wing yesterday for 100c.

So 2 Reveals are 12c, the base is 30c and the value just went to 60c -> profit

Whakano reveals on the same blueprint are roughly +1000 markers so 2c more expensive, still good.

It has always been a save bet on unusual gems, the others, not so much - hence the checking before i do it without going to trade :)
