### ISSUE TITLE
[Feature] Pricecheck Gem Corruptions

### ISSUE THREAD

**Issue by Sykh** [SnosMe/awakened-poe-trade#747]
I find it sometimes hard to check if a gem is worth the time to level (and vaal), would it be possible to pull gem prices from poe.ninja for corruptions?

Like i pricecheck Molten Shell it shows me the price for
- 21 20
- 20 23
- Vaal 20 20

In the style of breach stones for example where you can see the price of the others when you check one (which is super nice)

Not the double corrupt variations since if you spend that kind of money you probably did your research...

**Comment by SnosMe** [comment]
> Not the double corrupt variations since if you spend that kind of money you probably did your research...

You need 5 minutes to do research (and not to forget about attributes of your character), and a lot more hours to level up them to 20. I simply don't see the reason why you would level 20c gems instead of 50c ones just because you were lazy to spend 5 minutes on poe.ninja and made decision on price shown in APT as suggested in this feature request.

Also, there are no graphs and confidence levels shown in "related items" module, which I consider important in long term gem leveling too.
