### ISSUE TITLE
Cannot install.

### ISSUE THREAD

**Issue by lelefi** [SnosMe/awakened-poe-trade#8]
hi
im on win 10 1809 and the tool will not complete installation. its hanging half completed until i close it.

**Comment by SnosMe** [comment]
Unfortunately, there is nothing I can do about it. The installer is created automatically. I’m sure you tried both methods of the installation path option, but just in case, I’ll ask you to do it.

**Comment by lelefi** [comment]
tried different paths and admin/no admin, both with the same result. its weird cause the earlier version worked, although it didnt install for a friend so i sent him my folder.

**Comment by SnosMe** [comment]
I googled a little and [found this](https://stackoverflow.com/questions/56958787/nsis-build-does-not-install-the-electron-application-on-windows-the-installer-e).

Have you tried uninstalling through the control panel and rebooting your PC?

I have a laptop, as well as Windows Sandbox, can you describe the steps in order so that I can repeat them? (when you first installed which version. then deleted it and decided to wait for the update? did you see it and decided to install it again?).

**Comment by lelefi** [comment]
i didnt uninstall, i just deleted the old files, maybe thats causing the issue.
steps:
(0.1.1 worked as admin)
1. deleted 0.1.1 in desktop folder, poe running in background as limited user
2. downloaded 0.2.0
3. tried to install into same folder location as 0.1.1 was in.

**Comment by lelefi** [comment]
i got an installed version from a friend, used the uninstaller in the folder and now im able to install awakened poe trade

user error ^^
