### ISSUE TITLE
Black screen on 10006

### ISSUE THREAD

**Issue by profuter** [SnosMe/awakened-poe-trade#876]
I get a black screen, If I see overlay with prices more than 5-10 seconds, and game client is crashing constantly with the error "The GPU device instance has been suspended..." 
Close down Awakened trade not resolve black screen. Only reboot.

--disable-gpu  on link either not working.

GPU
Ati radeon R7 360

P.S. With poe overlay game periodically crashed too without black screen, just POE close without any messages. 

Without APOE and "poe overlay" game works fine.

**Comment by SnosMe** [comment]
```
--disable-gpu on link either not working.
```

It's enabled by default now. You have black screen for a different reason.

1. Update drivers.
2. Change the setting to the opposite you have right now.

Otherwise, unlucky, nothing to fix on my side.

![image](https://user-images.githubusercontent.com/4292308/212649188-50e41f5a-0ce5-4ec8-8ee8-454827b64a99.png)
