### ISSUE TITLE
Gem pricing not accurate

### ISSUE THREAD

**Issue by Diabolos** [SnosMe/awakened-poe-trade#889]
I ran into an instance of finding Anomalous Mana Leech .. OCR and the old method of checking gems both showed it as 192 chaos, but when I got out and it was revealed, it was roughly 3.7 divine orbs.
Not a problem with Awakened POE Trade itself, but something in the valuation part of the gem price check, the Awakened POE Trade checker I use with ctrl+D worked fine, and was on-target with POE Trade.

Not knocking the OCR at all, I love it, but it needs some refinement if possible.

**Comment by EldritchEevee** [comment]
If the gem is corrupted, and you enable "Corrupted" in the trade menu, it'll show **both** corrupted **AND** Uncorrupted gems.
The check for "corrupted" in a browser's tab is never set unless the gem is uncorrupted. Not sure when this was changed.

Doesn't require OCR to check.

**Comment by SnosMe** [comment]
@Diabolos The prices are from poe.ninja. In the Heist you get 14-16lvl gems which fall into lvl16 category on poe.ninja, and because this category has the most listings it's the most reliable for pricing.
Anomalous Mana Leech does look very suspicious, what caused it to double in price lately?
![image](https://user-images.githubusercontent.com/4292308/216769237-cd4734c7-1a62-4e5f-a3df-c841a4fd3f01.png)

If you know what kind of refinement I can do, we can discuss it here. 
I think all that matters is relative order of gems, and I'm sure Anomalous Mana Leech was the first in the list.

**Comment by SnosMe** [comment]
@EldritchEevee corrupted gems (<=20lvl or qual) aren't superior to normal ones, so it makes sense to show both. This changed at least a year ago, I think.

**Comment by Diabolos** [comment]
Fair enough, I was not sure if something was wrong, but you explained how it works, and I am ok with that.
Thanks for the work on APOET! 💯
