### ISSUE TITLE
DONT JUST STOP SUPPORTING AN OS WITHOUT WARNING

### ISSUE THREAD

**Issue by Conqueror933** [SnosMe/awakened-poe-trade#905]
FFS at least provide a download for the old version that still works!

and display a warning on the update that it will brick the version

what is wrong with you

**Comment by WasabiCannon** [comment]
Could you provide some more context to this?

Was about to make a thread about my own issue but wondering if we are having the same problems.
Could not run the installer on Win10 and noticed on the download page it onlys lists Win11. Assuming you are in the same boat sticking with Win 10 and having issues with Awakened PoE Trade.

**Comment by SnosMe** [comment]
You can download older version #904
Since day one on the Downloads Page, it was shown "Windows 10". The fact that it worked on win7 was just lucky.

Warning would be good, but I don't have enough time to care for this fraction of people.

![image](https://user-images.githubusercontent.com/4292308/230712351-a3227efc-0838-4404-97b2-7ecd78c81b1f.png)
